name: releaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release - foldcomments
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'foldcomments.zip'
          path: 'foldcomments'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload Release - foldcomments
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}